# Generated by Django 2.2.2 on 2019-06-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190619_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.IntegerField(help_text='Book Pages', max_length=50, null=True),
        ),
    ]
