# Generated by Django 2.2.2 on 2019-06-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_book_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='City Name', max_length=100, null=True)),
                ('state', models.CharField(help_text='State', max_length=100, null=True)),
            ],
        ),
    ]
