# Generated by Django 2.2.2 on 2019-06-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_book_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Purchaser Name', max_length=100, null=True)),
                ('ID', models.CharField(help_text='ID no', max_length=100, null=True)),
                ('date_of_purchase', models.DateField(blank=True, null=True, verbose_name='Purchased On')),
                ('date_of_return', models.DateField(blank=True, null=True, verbose_name='Returning On')),
            ],
        ),
    ]
