# Generated by Django 2.2.2 on 2019-06-20 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20190620_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='member_id',
        ),
    ]
