# Generated by Django 2.2.2 on 2019-06-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_member_member_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='date_of_return',
            new_name='date_of_returning',
        ),
        migrations.AlterField(
            model_name='member',
            name='member_name',
            field=models.CharField(help_text='Name of Author', max_length=100, null=True),
        ),
    ]
